language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
- oraclejdk7  
before_script:
- mvn install -pl qa-tools
script:
- mvn scoverage:report

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
